# Generated by Django 6.0.3 on 2026-08-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('peso', models.FloatField()),
                ('valor', models.FloatField()),
                ('observacao', models.CharField(max_length=255)),
            ],
        ),
    ]
