# Generated by Django 6.0.3 on 2026-08-26 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carga', '0001_initial'),
        ('viagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.viagem'),
        ),
    ]
