# Generated by Django 6.0.3 on 2026-08-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('quilometragem', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('capacidade_carga', models.FloatField()),
            ],
        ),
    ]
